# SMS Gateway
com.hp.sms.ip: 127.0.0.1
com.hp.sms.url: http://gw.api.tbsandbox.com/router/rest
com.hp.sms.appkey: 1023309955
com.hp.sms.secret: sandboxa4589aff503e51cf0695adedb
com.hp.sms.signName: 身份验证
com.hp.sms.smsTemplateCode: SMS_5037364
# Spring
spring.profiles.active: dev


